postgis container seems now to be working with lgd settings

diff --git a/lgd-docker/2022/lgd-docker/lgd-db/Dockerfile b/lgd-docker/2022/lgd-docker/lgd-db/Dockerfile
--- a/lgd-docker/2022/lgd-docker/lgd-db/Dockerfile
+++ b/lgd-docker/2022/lgd-docker/lgd-db/Dockerfile
@@ -3,13 +3,7 @@ MAINTAINER Claus Stadler <cstadler@informatik.uni-leipzig.de>
 
 RUN apk add gettext
 
-# Setting sysctls is done via docker compose (using the line below will give a read only filesystem error)
-# RUN echo "kernel.shmmax=4294967296" > /etc/sysctl.conf && sysctl -p
-
-# TODO It might be nicer if the DB config is updated from the environment on every container (re)start
-# COPY etc/postgresql/9.5/main/postgresql.conf.dist /app/postgresql/postgresql.conf.dist
-# etc/postgresql/9.5/main/postgresql.conf
-# COPY target/postgresql.conf /etc/postgresql/9.5/main/postgresql.conf
+COPY etc/postgresql/14/main/postgresql.conf.dist /conf/
 
 # Note: Ideally I would like to put the nominatim lib into e.g. /usr/lib/postgresql/${POSTGRES_VERSION}/lib/
 # However, the way nominatim's setup script works, it will create a stored proceduce in the database which looks up the library under a path
@@ -17,11 +11,10 @@ RUN apk add gettext
 COPY target/nominatim.so /app/nominatim/module/nominatim.so
 
 # HEALTHCHECK CMD ["psql", $DB_URL, "-c", "SELECT 1"]
-
-HEALTHCHECK --interval=1s --retries=180 CMD psql -U "$DB_USER" -c "SELECT 1" || exit 1
+# HEALTHCHECK --interval=1s --retries=180 CMD psql -U "$DB_USER" -c "SELECT 1" || exit 1
 
 COPY start.sh ./start.sh
-RUN chmod +x ./start.sh && sleep 1
+RUN chmod +x ./start.sh
 
 ENTRYPOINT ["./start.sh"]
 CMD ["postgres"]
